### ISSUE TITLE
Dockerfile does not build

### ISSUE THREAD

**Issue by maxandersen** [probot/smee.io#40]
using instructions in dockerfile gives an error about webpack missing.

```
docker build --build-arg BUILD_VERSION=0.0.3 --build-arg BUILD_DATE=2019-05-19 -t probot/smee-io:latest .
Sending build context to Docker daemon  686.6kB
Step 1/23 : ARG BUILD_VERSION
Step 2/23 : ARG BUILD_DATE
Step 3/23 : ARG PORT=3000
Step 4/23 : FROM node:lts-alpine as build-env
lts-alpine: Pulling from library/node
c9b1b535fdd9: Pull complete
6ad7c27326e7: Pull complete
968d8b4948da: Pull complete
a1ec837a6331: Pull complete
Digest: sha256:bba77d0ca8820b43af898b3c50d4e8b68dc703ebbd958319af2f21f2d3c309f5
Status: Downloaded newer image for node:lts-alpine
 ---> 927d03058714
Step 5/23 : WORKDIR /source
 ---> Running in 10e71be9fbe3
Removing intermediate container 10e71be9fbe3
 ---> 4716a7e8bbe8
Step 6/23 : ADD . .
 ---> d32ee15aa2c2
Step 7/23 : RUN npm install --production --unsafe-perm
 ---> Running in b360d0043782

> smee-server@0.0.3 postinstall /source
> npm run build


> smee-server@0.0.3 build /source
> webpack -p

sh: webpack: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! smee-server@0.0.3 build: `webpack -p`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the smee-server@0.0.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-01T21_27_29_137Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! smee-server@0.0.3 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smee-server@0.0.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-01T21_27_29_170Z-debug.log
```

**Comment by maxandersen** [comment]
by removing `--production` the build completes but then when running i.e. `smee -u http://localhost:3000/zaNTO0ugsV5Egh`

you get:
```
 smee -u http://localhost:3000/zaNTO0ugsV5Egh
(node:62119) UnhandledPromiseRejectionWarning: Error: The provided URL is invalid.
    at new Client (/usr/local/lib/node_modules/smee-client/index.js:14:13)
    at setup (/usr/local/lib/node_modules/smee-client/bin/smee.js:31:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/smee-client/bin/smee.js:35:1)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
(node:62119) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:62119) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by benzman81** [comment]
Same here, for docker build to work we need to remove —production. But after building the image like this everything works as expected.
