### ISSUE TITLE
Error verifying AWS simple notification service with 'smee' endpoint targeting to localhost api

### ISSUE THREAD

**Issue by jain-rajat** [probot/smee.io#42]
<h2> Please find the below stack trace: </h2>
<p>Forwarding https://smee.io/7qisD6OLdKOIcqPM to http://localhost:800/api/1/app/aws-email-webhook/
Connected https://smee.io/7qisD6OLdKOIcqPM</br>
_http_outgoing.js:690</br>
      throw new ERR_INVALID_ARG_TYPE('chunk', ['string', 'Buffer'], chunk);
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
    at ClientRequest.end (_http_outgoing.js:690:13)
    at Request._end (/usr/lib/node_modules/smee-client/node_modules/superagent/lib/node/index.js:1021:9)
    at Request.end (/usr/lib/node_modules/smee-client/node_modules/superagent/lib/node/index.js:777:15)
    at Client.onmessage (/usr/lib/node_modules/smee-client/index.js:35:9)
    at EventSource.emit (events.js:198:13)
    at _emit (/usr/lib/node_modules/smee-client/node_modules/eventsource/lib/eventsource.js:242:17)
    at parseEventStreamLine (/usr/lib/node_modules/smee-client/node_modules/eventsource/lib/eventsource.js:257:9)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/smee-client/node_modules/eventsource/lib/eventsource.js:217:11)
    at IncomingMessage.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
</p>
SMEE proxy url - <b> https://smee.io/7qisD6OLdKOIcqPM </b>
<p> Added above url in <b>AWS sns endpoint.</b> </br>
As soon as I request confirmation on AWS for this endpoint , above error is hitting. Please help me fix it! </br>
System Info: <b> Ubuntu 18.10</b>
Already done npm update and then installed smee-client
</p>

**Comment by JasonEtco** [comment]
@jain-rajat - I'm not sure how to help you here. There's nothing wrong with Smee, I'm assuming it's something to do with your AWS configuration. I'm going to close this because there's nothing for us to fix or change.
