### ISSUE TITLE
Patreon Webhook payload issue

### ISSUE THREAD

**Issue by CodingCamurai** [probot/smee.io#99]
when attempting to use the patreon webhook with smee.io, The server ends up hanging when trying to parse the payload. I get no response from the server until I shut down the smee client, then the server spits out this error:
`BadRequestError: request aborted
[server]     at IncomingMessage.onAborted (...node_modules\raw-body\index.js:238:10)
[server]     at IncomingMessage.emit (node:events:513:28)
[server]     at IncomingMessage._destroy (node:_http_incoming:224:10)
[server]     at _destroy (node:internal/streams/destroy:109:10)
[server]     at IncomingMessage.destroy (node:internal/streams/destroy:71:5)
[server]     at abortIncoming (node:_http_server:696:9)
[server]     at socketOnClose (node:_http_server:690:3)
[server]     at Socket.emit (node:events:525:35)
[server]     at TCP.<anonymous> (node:net:757:14)`

The same exact code works in production when getting the request directly from Patreon webhook.
Also the smee.io site is able to display the payload without issue, it just cant seem to forward it correctly to the target.

I created a super simple express server to test and make sure there wasn't another setting I had on my server that was interfering but go the same results:
`
import express from 'express'
import http from 'http'

const app = express()

app.post('/webhook/patreon', express.json(), (req, res) => {
    console.log('Received request')
    console.log(req.body)
	res.sendStatus(200)
})

const server = new http.Server(app)
const port = 3000
server.listen(port, () => {
	console.log('Listening on port', port)
})
`
I believe it has something to do with the payload being formatted differently from what is in the original webhook request, because removing the express.json() parsing does get the request to go through, but the body is empty in that case, so it is having trouble parsing the payload correctly.
I would guess it is something weird Patreon is doing with its payload that is not being accounted for since everyone else does not seem to have issues using it with other webhooks. I noticed a previous issue with content-length being changed from removing white-spacing causing a similar result so perhaps it is has something to do with that.

**Comment by bongvin070312120-spec** [comment]
smee -u https://smee.io/fChQI8aWSZbV5Ueh/

> នៅពេលព្យាយាមប្រើ patreon webhook ជាមួយ smee.io ម៉ាស៊ីនមេបញ្ចប់ដោយការគាំងនៅពេលព្យាយាមវិភាគ payload ។ ខ្ញុំមិនទទួលបានការឆ្លើយតបពីម៉ាស៊ីនមេទេរហូតដល់ខ្ញុំបិទកម្មវិធី smee បន្ទាប់មកម៉ាស៊ីនមេបង្ហាញកំហុសនេះ៖
> 
> ```
> BadRequestError: request aborted
> [server]     at IncomingMessage.onAborted (...node_modules\raw-body\index.js:238:10)
> [server]     at IncomingMessage.emit (node:events:513:28)
> [server]     at IncomingMessage._destroy (node:_http_incoming:224:10)
> [server]     at _destroy (node:internal/streams/destroy:109:10)
> [server]     at IncomingMessage.destroy (node:internal/streams/destroy:71:5)
> [server]     at abortIncoming (node:_http_server:696:9)
> [server]     at socketOnClose (node:_http_server:690:3)
> [server]     at Socket.emit (node:events:525:35)
> [server]     at TCP.<anonymous> (node:net:757:14)
> ```
> 
> កូដដូចគ្នានេះដំណើរការនៅក្នុងផលិតកម្មនៅពេលទទួលបានសំណើដោយផ្ទាល់ពី Patreon webhook។ លើសពីនេះ គេហទំព័រ smee.io អាចបង្ហាញ payload ដោយគ្មានបញ្ហា វាគ្រាន់តែមិនអាចបញ្ជូនបន្តវាបានត្រឹមត្រូវទៅកាន់គោលដៅ។
> 
> ខ្ញុំបានបង្កើតម៉ាស៊ីនបម្រើ express ដ៏សាមញ្ញមួយដើម្បីសាកល្បង និងធ្វើឱ្យប្រាកដថាមិនមានការកំណត់ផ្សេងទៀតដែលខ្ញុំមាននៅលើម៉ាស៊ីនបម្រើរបស់ខ្ញុំដែលជ្រៀតជ្រែកនោះទេ ប៉ុន្តែលទ្ធផលដូចគ្នា៖
> 
> import express from 'express'
> import http from 'http'
> 
> const app = express()
> 
> app.post('/webhook/patreon', express.json(), (req, res) => {
>     console.log('Received request')
>     console.log(req.body)
> 	res.sendStatus(200)
> })
> 
> const server = new http.Server(app)
> const port = 3000
> server.listen(port, () => {
> 	console.log('Listening on port', port)
> })
> ខ្ញុំជឿថាវាមានជាប់ទាក់ទងនឹង payload ដែលត្រូវបានធ្វើទ្រង់ទ្រាយខុសពីអ្វីដែលមាននៅក្នុងសំណើ webhook ដើម ពីព្រោះការដកការវិភាគ express.json() ចេញពិតជាធ្វើឱ្យសំណើឆ្លងកាត់ ប៉ុន្តែតួឯកសារគឺទទេក្នុងករណីនោះ ដូច្នេះវាមានបញ្ហាក្នុងការវិភាគ payload បានត្រឹមត្រូវ។ ខ្ញុំគិតថាវាជាអ្វីដែលចម្លែកដែល Patreon កំពុងធ្វើជាមួយ payload របស់វាដែលមិនត្រូវបានរាប់បញ្ចូលទេ ព្រោះអ្នកផ្សេងទៀតហាក់ដូចជាមិនមានបញ្ហាក្នុងការប្រើវាជាមួយ webhooks ផ្សេងទៀត។ ខ្ញុំបានកត់សម្គាល់ឃើញបញ្ហាមុនជាមួយ content-length ដែលត្រូវបានផ្លាស់ប្តូរពីការដក white-space ចេញ ដែលបណ្តាលឱ្យមានលទ្ធផលស្រដៀងគ្នា ដូច្នេះប្រហែលជាវាមានជាប់ទាក់ទងនឹងរឿងនោះ។

smee -u https://smee.io/fChQI8aWSZbV5Ueh

<blockquote><img src="/public/favicon.png" width="48" align="right"><div><strong><a href="https://smee.io/fChQI8aWSZbV5Ueh/">smee.io | Webhook deliveries</a></strong></div></blockquote>
<blockquote><img src="/public/favicon.png" width="48" align="right"><div><strong><a href="https://smee.io/fChQI8aWSZbV5Ueh">smee.io | Webhook deliveries</a></strong></div></blockquote>

**Comment by bongvin070312120-spec** [comment]
smee -u https://smee.io/T5PMN7SClCc6MSJT

<blockquote><img src="/public/favicon.png" width="48" align="right"><div><strong><a href="https://smee.io/T5PMN7SClCc6MSJT">smee.io | Webhook deliveries</a></strong></div></blockquote>
